#include "render.h"

/**
 * renderScreen - renders the pixels generated by raycasting
 */
void renderScreen(void)
{
	SDL_UpdateTexture(app.screen_texture, NULL, pxl.pixels,
				  SCREEN_WIDTH * 4);
	SDL_RenderCopy(app.renderer, app.screen_texture, NULL, NULL);
}

/**
 * renderPlayer - render player guns
 */
void renderPlayer(void)
{
	SDL_Rect dest;

	SDL_QueryTexture(player.gunTextures[player.numGun],
			 NULL, NULL, &dest.w, &dest.h);
	dest.h = 4 * dest.h;
	dest.w = 4 * dest.w;
	dest.x = (int) (SCREEN_WIDTH - dest.w) / 2;
	dest.y = SCREEN_HEIGHT - dest.h;

	SDL_RenderCopy(app.renderer, player.gunTextures[player.numGun],
		       NULL, &dest);
	if (player.gunTime > 0)
		player.gunTime--;
}

/**
 * renderall - render all sprints
 */
void renderAll(void)
{
	renderScreen();
	renderPlayer();
}
